
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
  
  cellarius-import-emails:
    image: cellarius-import-emails
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      IMAP_PALIDO_USERNAME: ${IMAP_PALIDO_USERNAME}
      IMAP_PALIDO_EMAIL_PASSWORD: ${IMAP_PALIDO_EMAIL_PASSWORD}
      IMAP_PALIDO_SERVER: ${IMAP_PALIDO_SERVER}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

  cellarius-ai-api:
    image: cellarius-ai-api
    restart: unless-stopped
    ports:
      - 8082:8082
  
  #gpt-neo-1-3B-docker:
  #  image: gpt-neo-1-3b-docker
  #  restart: unless-stopped
  #  ports:
  #    - 8001:8001